- name: Run php artisan
  shell: "{{item}} chdir=/var/www/html/laravel"
  loop:
    - php artisan key:generate --force
    - php artisan config:cache
    - php artisan config:clear

- name: Run artisan migrate
  become: true
  shell: >
    php artisan migrate:fresh --force
    chdir=/var/www/html/laravel

- name: Run seed migrate
  become: true
  shell: >
    php artisan migrate --seed --force
    chdir=/var/www/html/laravel
